In [2]:
import torch
import torch.nn as nn

In [4]:
input=torch.randn(2,4,8)
print(input)

tensor([[[-0.6160, -1.8303,  0.4108, -1.1182, -0.8021,  0.0576, -0.5731,
          -0.5732],
         [-0.8159, -0.6302,  0.1083,  0.2302,  1.5967, -0.4207, -1.0505,
          -0.8319],
         [ 0.3674, -0.4683,  0.9968, -0.6287,  0.2381, -0.8051, -1.4777,
           2.3898],
         [-0.9409,  0.6139, -0.6303, -1.1925,  1.3386, -1.5497,  0.3190,
           0.2400]],

        [[-0.3845,  0.5598,  0.7028, -0.5855,  1.3885,  0.8629,  0.0202,
          -1.8617],
         [-0.2009, -1.1039,  0.0138,  0.6810, -0.0605, -0.3840, -0.4033,
          -0.5464],
         [ 0.6966,  0.5056,  0.4650, -0.3434, -0.4110, -0.9212, -0.9467,
          -0.6201],
         [ 1.8557,  1.5105,  0.6874, -0.8783, -2.1512, -0.1695, -0.9753,
           0.0033]]])


In [7]:
t=torch.ones((8))
print(t)
print(t*input)

tensor([1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[[-0.6160, -1.8303,  0.4108, -1.1182, -0.8021,  0.0576, -0.5731,
          -0.5732],
         [-0.8159, -0.6302,  0.1083,  0.2302,  1.5967, -0.4207, -1.0505,
          -0.8319],
         [ 0.3674, -0.4683,  0.9968, -0.6287,  0.2381, -0.8051, -1.4777,
           2.3898],
         [-0.9409,  0.6139, -0.6303, -1.1925,  1.3386, -1.5497,  0.3190,
           0.2400]],

        [[-0.3845,  0.5598,  0.7028, -0.5855,  1.3885,  0.8629,  0.0202,
          -1.8617],
         [-0.2009, -1.1039,  0.0138,  0.6810, -0.0605, -0.3840, -0.4033,
          -0.5464],
         [ 0.6966,  0.5056,  0.4650, -0.3434, -0.4110, -0.9212, -0.9467,
          -0.6201],
         [ 1.8557,  1.5105,  0.6874, -0.8783, -2.1512, -0.1695, -0.9753,
           0.0033]]])


In [13]:
print(torch.mean(input,dim=-1))
print(input-torch.mean(input,dim=-1).unsqueeze(-1))

tensor([[-0.6306, -0.2268,  0.0765, -0.2252],
        [ 0.0878, -0.2505, -0.1969, -0.0147]])
tensor([[[ 0.0146, -1.1998,  1.0414, -0.4876, -0.1715,  0.6882,  0.0574,
           0.0574],
         [-0.5891, -0.4035,  0.3350,  0.4569,  1.8235, -0.1940, -0.8237,
          -0.6051],
         [ 0.2908, -0.5448,  0.9203, -0.7053,  0.1615, -0.8816, -1.5542,
           2.3133],
         [-0.7157,  0.8391, -0.4050, -0.9673,  1.5639, -1.3245,  0.5442,
           0.4653]],

        [[-0.4723,  0.4720,  0.6150, -0.6733,  1.3007,  0.7751, -0.0677,
          -1.9495],
         [ 0.0496, -0.8533,  0.2643,  0.9315,  0.1900, -0.1334, -0.1527,
          -0.2959],
         [ 0.8935,  0.7025,  0.6619, -0.1465, -0.2141, -0.7243, -0.7498,
          -0.4232],
         [ 1.8704,  1.5252,  0.7021, -0.8636, -2.1365, -0.1548, -0.9607,
           0.0179]]])


In [21]:
class LayerNorm(nn.Module):
    def __init__(self,input):
        super().__init__()
        self.alpha=torch.ones((input.size(-1)))
        self.beta=torch.zeros((input.size(-1)))
        self.eps=1e-12
    def forward(self,x):
        mean=torch.mean(x,dim=-1).unsqueeze(-1)
        var= ((torch.sum(((x - mean)**2),dim=-1))/x.size(-1)).unsqueeze(-1)
        output = self.alpha*((x-mean)/torch.sqrt(var+self.eps)) + self.beta
        return output

In [22]:
print(input)

tensor([[[-0.6160, -1.8303,  0.4108, -1.1182, -0.8021,  0.0576, -0.5731,
          -0.5732],
         [-0.8159, -0.6302,  0.1083,  0.2302,  1.5967, -0.4207, -1.0505,
          -0.8319],
         [ 0.3674, -0.4683,  0.9968, -0.6287,  0.2381, -0.8051, -1.4777,
           2.3898],
         [-0.9409,  0.6139, -0.6303, -1.1925,  1.3386, -1.5497,  0.3190,
           0.2400]],

        [[-0.3845,  0.5598,  0.7028, -0.5855,  1.3885,  0.8629,  0.0202,
          -1.8617],
         [-0.2009, -1.1039,  0.0138,  0.6810, -0.0605, -0.3840, -0.4033,
          -0.5464],
         [ 0.6966,  0.5056,  0.4650, -0.3434, -0.4110, -0.9212, -0.9467,
          -0.6201],
         [ 1.8557,  1.5105,  0.6874, -0.8783, -2.1512, -0.1695, -0.9753,
           0.0033]]])


In [23]:
mean=torch.mean(input,dim=-1).unsqueeze(-1)
print(mean)

tensor([[[-0.6306],
         [-0.2268],
         [ 0.0765],
         [-0.2252]],

        [[ 0.0878],
         [-0.2505],
         [-0.1969],
         [-0.0147]]])


In [24]:
var=((torch.sum(((input-mean)**2),dim=-1))/input.size(-1)).unsqueeze(-1)
print(var)

tensor([[[0.4089],
         [0.6548],
         [1.2870],
         [0.8786]],

        [[0.9219],
         [0.2291],
         [0.3829],
         [1.5719]]])


In [25]:
output=(input-mean)/torch.sqrt(var+1e-12)
print(output)

tensor([[[ 0.0228, -1.8762,  1.6285, -0.7625, -0.2682,  1.0761,  0.0898,
           0.0897],
         [-0.7280, -0.4986,  0.4140,  0.5647,  2.2535, -0.2397, -1.0180,
          -0.7478],
         [ 0.2563, -0.4803,  0.8112, -0.6217,  0.1424, -0.7771, -1.3700,
           2.0391],
         [-0.7635,  0.8952, -0.4321, -1.0320,  1.6684, -1.4131,  0.5806,
           0.4964]],

        [[-0.4919,  0.4916,  0.6405, -0.7013,  1.3547,  0.8073, -0.0705,
          -2.0304],
         [ 0.1036, -1.7827,  0.5521,  1.9460,  0.3970, -0.2788, -0.3191,
          -0.6182],
         [ 1.4440,  1.1353,  1.0696, -0.2368, -0.3460, -1.1705, -1.2117,
          -0.6839],
         [ 1.4918,  1.2165,  0.5600, -0.6888, -1.7041, -0.1235, -0.7662,
           0.0143]]])


In [26]:
ln=LayerNorm(input)
output=ln(input)
print(output)

tensor([[[ 0.0228, -1.8762,  1.6285, -0.7625, -0.2682,  1.0761,  0.0898,
           0.0897],
         [-0.7280, -0.4986,  0.4140,  0.5647,  2.2535, -0.2397, -1.0180,
          -0.7478],
         [ 0.2563, -0.4803,  0.8112, -0.6217,  0.1424, -0.7771, -1.3700,
           2.0391],
         [-0.7635,  0.8952, -0.4321, -1.0320,  1.6684, -1.4131,  0.5806,
           0.4964]],

        [[-0.4919,  0.4916,  0.6405, -0.7013,  1.3547,  0.8073, -0.0705,
          -2.0304],
         [ 0.1036, -1.7827,  0.5521,  1.9460,  0.3970, -0.2788, -0.3191,
          -0.6182],
         [ 1.4440,  1.1353,  1.0696, -0.2368, -0.3460, -1.1705, -1.2117,
          -0.6839],
         [ 1.4918,  1.2165,  0.5600, -0.6888, -1.7041, -0.1235, -0.7662,
           0.0143]]])


let's actually understand the journey of the activation functions, they are used to better learn the complex patterns without them doesn't matter stacking Many layers it's just a linear thing, there is no non linearities
The journey was something like this:
Sigmoid -> Tanh -> ReLU -> GeLU -> SwiGLU
Sigmoid(x)=1/1+e^-x ( used in binary classification)
Tanh -> centered at zero, but still if a neuron falls into the staright region it's hard to recover
ReLU -> max(0,x) -> Dead neuron problems
GELU -> x * φ(x) the function is gaussian cumulative distributive function

yes
